baseURL = "https://yogisec.github.com/test-website"
languageCode = "en-us"
title = "jellyparks"

[menu]
[[menu.main]]
  identifier = 'thing1'
  name = 'thing1'
  url = '/thing1/'
  weight = -110


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = 'rainbow_dash'
    tabWidth = 4